# Generated by Django 3.1.6 on 2021-03-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0004_auto_20210225_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='events',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
