# Generated by Django 3.1.6 on 2021-03-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='events',
        ),
    ]
