# Generated by Django 3.1.6 on 2021-03-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210308_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='concluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
