# Generated by Django 3.1.6 on 2021-03-04 02:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20210303_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='emojis')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='active',
        ),
        migrations.AddField(
            model_name='events',
            name='conclusion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('I', 'Inactive'), ('A', 'Active'), ('C', 'Concluded')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='gift',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gift',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='game_length',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='gift',
            name='emoji',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='events.emoji'),
            preserve_default=False,
        ),
    ]
