# Generated by Django 3.1.6 on 2021-03-04 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210304_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='emoji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.emoji'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
