# Generated by Django 3.1.6 on 2021-03-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210304_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='activated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='concluded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
