# Generated by Django 3.1.6 on 2021-03-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210305_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
