name: Deploy to Staging Environment
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  deploy:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Calculate Version Number
        run: echo "VERSION_NO=$ss_{GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Zip Source Files
        run: |
          cd secret_santa
          zip -r ~/${{ env.VERSION_NO }}.zip $(ls -A)
          ls ~
      - name: Authenticate AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET }}
          aws-region: ap-southeast-2
      - name: Upload Source Code to S3
        run: >
          aws s3api put-object
          --bucket ${{ secrets.AWS_BUCKET_NAME }}
          --key ss/${{ env.VERSION_NO }}.zip
          --body ~/${{ env.VERSION_NO }}.zip
      - name: Create new EB Application Version
        run: >
          aws elasticbeanstalk create-application-version
          --application-name SecretSanta
          --version-label ${{ env.VERSION_NO }}
          --source-bundle S3Bucket=${{ secrets.AWS_BUCKET_NAME }},S3Key=ss/${{ env.VERSION_NO }}.zip
      - name: Deploy New Version in Staging Environment
        run: >
          aws elasticbeanstalk update-environment
          --application-name SecretSanta
          --environment-name SecretSanta-staging
          --version-label ${{ env.VERSION_NO }}
