on: push

jobs:
  deploy:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Calculate File Name
        run: echo "filename=ss_$( git rev-parse --short HEAD )" > $GITHUB_ENV
      - name: Zip Source Files
        run: |
          cd secret_santa
          zip -r ~/${{ env.filename }}.zip $(ls -A)
          ls ~
      - name: Authenticate AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET }}
          aws-region: ap-southeast-2
      - name: Upload Source Code to S3
        run: >
          aws s3api put-object
          --bucket ${{ secrets.AWS_BUCKET_NAME }}
          --key ss/${{ env.filename }}.zip
          --body ~/${{ env.filename }}.zip
      - name: Create new EB Application Version
        run: >
          aws elasticbeanstalk create-application-version
          --application-name SecretSanta
          --version-label ${{ env.filename }}
          --source-bundle S3Bucket=${{ secrets.AWS_BUCKET_NAME }},S3Key=ss/${{ env.filename }}.zip
      - name: Deploy New Version in Staging Environment
