name: Deploy to Staging Environment
on:
  push:

jobs:
  deploy:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Calculate Version Number
        run: echo "VERSION_NO=ss_${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Authenticate AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET }}
          aws-region: ap-southeast-2
      - name: Render Task Definition
        run: >
        aws ecs describe-task-definition
        --task-definition secret-santa-web-application-server
        &#62; task_definition.json


